### ISSUE TITLE
Modify workflow to not run on deploy for now

### ISSUE THREAD

**Issue by DJSethDuncan** [DJSethDuncan/react-apod#9]
Not doing any real deploys atm, so we can remove the step.

in `.github/workflows/node.js.yml` 

change

```
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
```

to

```
on:
  pull_request:
    branches: ["main"]
```
